# Generated by Django 4.2.23 on 2025-07-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
