# Generated by Django 4.2.23 on 2025-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_menteementorlink_mentees_and_more'),
        ('communications', '0002_requests_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='recipient',
        ),
        migrations.AddField(
            model_name='requests',
            name='recipients',
            field=models.ManyToManyField(related_name='received_requests', to='users.userdetails'),
        ),
    ]
