# Generated by Django 4.2.23 on 2025-06-22 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenteeDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('goals', models.JSONField(default=list)),
                ('learning_preferences', models.JSONField(default=list)),
                ('expectations', models.TextField()),
                ('meeting_preferences', models.JSONField(default=list)),
                ('neurodivergent_conditions', models.JSONField(default=list)),
                ('commitment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roles', models.JSONField(default=list)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation_start_date', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('qualifications', models.TextField()),
                ('experience', models.TextField()),
                ('commitment', models.CharField(max_length=255)),
                ('meeting_preferences', models.JSONField(default=list)),
                ('neurodivergent_conditions', models.JSONField(default=list)),
                ('user_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_details', to='users.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='MenteeMentorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.menteedetails')),
                ('mentors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentordetails')),
            ],
        ),
        migrations.AddField(
            model_name='menteedetails',
            name='mentors',
            field=models.ManyToManyField(through='users.MenteeMentorLink', to='users.mentordetails'),
        ),
        migrations.AddField(
            model_name='menteedetails',
            name='user_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_details', to='users.userdetails'),
        ),
    ]
