# Generated by Django 4.2.23 on 2025-06-23 03:34

from django.db import migrations, models
import users.helpers.random_profile_pic_name


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordetails',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.helpers.random_profile_pic_name.profile_pic_upload_to),
        ),
    ]
