# Generated by Django 4.2.23 on 2025-06-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mentordetails_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteementorlink',
            name='mentees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.menteedetails'),
        ),
        migrations.AlterField(
            model_name='menteementorlink',
            name='mentors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.mentordetails'),
        ),
        migrations.AlterField(
            model_name='mentordetails',
            name='experience',
            field=models.TextField(default=''),
        ),
    ]
