# Generated by Django 4.2.23 on 2025-07-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_menteementorlink_mentees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteementorlink',
            name='mentees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.menteedetails'),
        ),
        migrations.AlterField(
            model_name='menteementorlink',
            name='mentors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentordetails'),
        ),
    ]
