name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # ✅ Check out code FIRST
      - uses: actions/checkout@v4

      # ✅ Install frontend dependencies
      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      # ✅ Install Python dependencies
      - name: Install pip and backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: backend

      # ✅ Create .env for Django
      - name: Write .env file from GitHub secrets
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "ENV=dev" >> .env
        working-directory: backend

      # ✅ Build frontend (assumes `ng` is installed via package.json)
      - name: Build frontend
        run: npm run build
        working-directory: frontend

      # ✅ Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MIND_4_MINDS }}
          channelId: live
          projectId: mind-4-minds
